# Generated by Django 6.0.2 on 2026-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurant_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='features',
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_budget',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_spicy',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
