# Generated by Django 6.0.2 on 2026-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pref_budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pref_spicy',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(default='Prayagraj', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='locality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
