# Generated by Django 6.0.2 on 2026-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
